### ISSUE TITLE
Reading RAPL MSRs from user-space

### ISSUE THREAD

**Issue by kaposnick** [l3nkz/eteam-rt#4]
Hi, this is a generic question regarding your paper [1] , which I identify as a core concept behind [2].

I have been trying improve the accuracy of the RAPL measurements, synchronizing the start of my <code>foo</code> method with a RAPL update, and measuring the duration between the end of my method and the next RAPL update. I have been majorly inspired by your implementation in [3]. However, in my case, the read of RAPL MSRs is done in the user-space. It's worth mentioning that my <code>foo</code> method finishes in the order of milliseconds, so high accuracy measurements are critical for my application. 

I am able to read the MSRs from user-space through the ````/dev/cpu/x/msr```` pseudo file. Still though, the quality of the results is not as expected. 

Also, in [1], you mention:
> On the Intel Architecture,  this (reading MSRs) is only possible in privileged kernel mode. Hence, we require kernel-level support for energy readings.

I want to ask whether is your reference related to the extra added latency passing from user-space to kernel-space during the ````open````, ````read```` syscalls, which would undermine the quality of the results. If not, what it refers to?

Also, do you think that this extra added latency would significantly affect accuracy?

Thanks a lot!

References:
- [1] [Measuring Energy Consumption for Short Code Paths Using RAPL](https://os.inf.tu-dresden.de/papers_ps/greenmetrics2012-rapl.pdf)
- [2] [E-Team: Practical Energy Accounting for Multi-Core Systems](https://www.usenix.org/system/files/conference/atc17/atc17-smejkal.pdf)
- [3] https://github.com/l3nkz/eteam/blob/049f856ddc463489cd0326f0719d05f053035890/kernel/sched/energy.c#L680

**Comment by l3nkz** [comment]
Hi, 
First of all, sorry for the delayed response!

Yes, using the RAPL MSR to measure really short running functions from userspace is not really possible. The overhead/latency that is introduced when you access the MSR from userspace via the `/dev/cpu/0/msr` file will negatively influence your measurement to a degree, that your measurement is totally useless. In the E-Team paper we use this method within the kernel, where we have direct access to the MSRs and hence don't have this overhead (we only have the latency of the `rdmsr` instruction itself). 

However, what might help you is to create a kernel module that exposes you a different RAPL interface. Something, where you can query the current RAPL energy counter but in a synchronous fashion. Meaning, that the kernel module will wait for a MSR update upon call and returns the current (updated) value as well as the time that it waited for the update. With that interface, you should be able to measure really short functions from userspace as well. You just need to account for the user-kernel transition, but this should be a nearly constant factor, that you can measure before the actual measurement and account accordingly in your result.

I hope I could help you!

**Comment by kaposnick** [comment]
Thanks a lot for your help! The high variance we observe across different runs seems to originate from the user-kernel transition plus the ``rdmsr``, which results to high noise. The kernel module synchronous read is a good approach so the only variable to figure out is the user-kernel transition latency measurement.
